## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

services:
  app:
    build:
      context: ./images/nginx/1.24
      dockerfile: Dockerfile
    #image: magento/magento-nginx-base:1.24
    container_name: app
    ports:
      - "443:443"
    volumes: &appvolumes
      #- ~/.composer:/var/www/.composer:cached
      #- ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      #- ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    env_file: env/nginx.env

  phpfpm:
    build:
      context: ./images/phpfpm/8.3
      dockerfile: Dockerfile
    #image: magento/php-fpm:8.3
    container_name: phpfpm
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts

  db:
    build:
      context: ./images/mysql/8.0
      dockerfile: Dockerfile
    #image: magento/mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql


  #redis:
  #  image: redis:7.2-alpine
  #  ports:	
  #    - "6379:6379"

  ## If you wish to use Elasticsearch, comment out opensearch image above and
  ## uncomment this block. Do the same in the composer.healthcheck.yaml file.
  # Additionally, if you are performing the manual setup, you will need to
  # update the bin/setup command to use the $ES_HOST variable as the value for
  # the --elasticsearch-host argument passed to bin/magento setup:install.
  elasticsearch:
    build:
      context: ./images/elasticsearch/7.17
      dockerfile: Dockerfile
    #image: magento/elasticsearch:7.17.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/elasticsearch.env
    environment:
      - "discovery.type=single-node"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      ## Uncomment to set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ## Uncomment to increase the virtual memory map count
      #- "max_map_count=262144"

  #rabbitmq:
  #  image: markoshust/magento-rabbitmq:3.12-0
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"
  #  volumes:
  #    - rabbitmqdata:/var/lib/rabbitmq
  #  env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"

  ## Cloudflare tunnel support, uncomment to enable
  #tunnel:
  #  container_name: cloudflared-tunnel
  #  image: cloudflare/cloudflared:latest
  #  command: tunnel run
  #  env_file: env/cloudflare.env

  ## Blackfire support, uncomment to enable
  #blackfire:
  #  image: blackfire/blackfire:2
  #  ports:
  #    - "8307"
  #  env_file: env/blackfire.env

  ## Selenium support, uncomment to enable
  #selenium:
  #  image: selenium/standalone-chrome-debug:3.8.1
  #  ports:
  #    - "5900:5900"
  #  extra_hosts: *appextrahosts

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
