services:
  nginx:
    build:
      context: ./images/nginx/1.24
      dockerfile: Dockerfile
    container_name: me2uet.io.vn
    volumes: &appvolumes
      - appdata:/var/www/html
      - sockdata:/sock
    env_file: env/nginx.env
    networks:
      - magento

  phpfpm:
    build:
      context: ./images/phpfpm/8.3
      dockerfile: Dockerfile
    container_name: phpfpm
    volumes: *appvolumes
    env_file: env/phpfpm.env
    networks:
      - magento

  db:
    build:
      context: ./images/mysql/8.0
      dockerfile: Dockerfile
    container_name: db
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - magento


  redis:
   image: redis:7.2-alpine
   container_name: redis
   networks:
      - magento
      
  elasticsearch:
    build:
      context: ./images/elasticsearch/7.17
      dockerfile: Dockerfile
    container_name: elasticsearch
    env_file: env/elasticsearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - magento
    
  tunnel:
   container_name: cloudflared-tunnel
   image: cloudflare/cloudflared:latest
   command: tunnel run
   env_file: env/cloudflare.env
   networks:
      - magento
 
  # mailcatcher:
  #   image: sj26/mailcatcher
  #   container_name: mailcatcher
  #   ports:
  #     - "1080:1080"
  #   networks:
  #     - magento

volumes:
  appdata:
  dbdata:
  sockdata:
networks:
  magento:
    driver: bridge
