#!/usr/bin/env bash

f_to_copy=${1:"--all"}
SRC=${2:"source"}

if [ "$1" == "--all" ]; then
  docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/./ "$SRC/"
  echo "Completed copying all files from container to host"
else
  if [ -f "$SRC/$f_to_copy" ]; then
    docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/"$f_to_copy" "$SRC/$f_to_copy"
  else
    docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/"$(dirname "$f_to_copy")" "$REAL_SRC/${f_to_copy}"
  fi
  echo "Completed copying $f_to_copy from container to host"
fi
