#!/usr/bin/env bash

f_to_copy=${1}

if [ -z "$1" ]; then
    f_to_copy="--all"
fi

SRC=$(cd -P "source" && pwd)
if [ ! -d "$SRC" ]; then
  mkdir -p "$SRC"
fi

if [ "$f_to_copy" == "--all" ]; then
  sudo docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/./ "$SRC/"
  echo "Completed copying all files from container to host"
else
  if [ -f "$SRC/$f_to_copy" ]; then
    sudo docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/"$f_to_copy" "$SRC/$f_to_copy"
  else
    sudo docker cp "$(command/docker-compose ps -q phpfpm)":/var/www/html/magento/"$(dirname "$f_to_copy")" "$REAL_SRC/${f_to_copy}"
  fi
  echo "Completed copying $f_to_copy from container to host"
fi
