#!/usr/bin/env bash

# Set variables for context name and server information
CONTEXT_NAME="remote-context"
SERVER_IP="ip"
CERT_DIR="path_to_cert"
PORT=port_of_remote

if docker context ls --quiet | grep -q "^$CONTEXT_NAME$"; then
    echo "Context exists: $CONTEXT_NAME"
    docker context use $CONTEXT_NAME
else
    echo "Context $CONTEXT_NAME does not exist. Creating new one"
    docker context create $CONTEXT_NAME \
  	--docker "host=tcp://$SERVER_IP:$PORT,ca=$CERT_DIR/ca.pem,cert=$CERT_DIR/client-cert.pem,key=$CERT_DIR/client-key.pem" \
  	--description "Docker context with TLS for remote server"

    docker context use $CONTEXT_NAME
fi

exec bash
